[ad]
SRV-ADS01 ansible_host=10.0.4.2 ansible_user=Administrator ansible_password="A!dmin84/" ansible_connection=winrm ansible_winrm_transport=basic ansible_port=5985 ansible_winrm_server_cert_validation=ignore
