[linux]
SRV-PKI        ansible_host=10.0.4.3       ansible_user=ansible       ansible_ssh_private_key_file=~/.ssh/ansible_ed25519
SRV-SSO        ansible_host=10.0.4.4       ansible_user=ansible       ansible_ssh_private_key_file=~/.ssh/ansible_ed25519
SRV-INTRANET   ansible_host=10.0.4.5       ansible_user=ansible       ansible_ssh_private_key_file=~/.ssh/ansible_ed25519
IT-GRAPHANA    ansible_host=10.0.3.3       ansible_user=ansible       ansible_ssh_private_key_file=~/.ssh/ansible_ed25519
SRV-ANSIBLE    ansible_host=192.168.203.5  ansible_connection=local   ansible_user=ansible_admin

[windows]
SRV-ADS01      ansible_host=10.0.4.2       ansible_user=ansible_admin ansible_password=A!dmin84/ ansible_connection=winrm ansible_winrm_transport=ntlm ansible_winrm_server_cert_validation=ignore
IT-MGMT        ansible_host=10.0.3.4       ansible_user=ansible_admin ansible_password=A!dmin84/ ansible_connection=winrm ansible_winrm_transport=ntlm ansible_winrm_server_cert_validation=ignore

[linux:vars]
ansible_become=yes

[windows:vars]
ansible_port=5985
