db=postgres
db-username=keycloak
db-password=A!dmin84/
db-url=jdbc:postgresql://localhost/keycloak
http-enabled=true
http-port=8080
hostname=sso.itway.local
hostname-admin=sso.itway.local
hostname-strict=false
hostname-strict-https=true
hostname-strict-backchannel=false
proxy=edge
log=console,file
log-file=/var/log/keycloak/keycloak.log
