# -*- mode: ruby -*-
# vi: set ft=ruby :
# PROXY-DMZ - itway.fr / webmail.itway.fr / sso.itway.fr
# IP : 10.0.5.2 | DMZ-VLAN 10.0.5.0/28 | Gateway : 10.0.5.1 (RT-DMZ)
# Debian 12 + NGINX Reverse Proxy

Vagrant.configure("2") do |config|
  config.vm.box      = "debian/bookworm64"
  config.vm.hostname = "proxy-dmz"

  config.vm.network "private_network",
    ip: "10.0.5.2",
    virtualbox__intnet: "dmz-vlan"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "PROXY-DMZ"
    vb.memory = 1024
    vb.cpus   = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -qq
    apt-get install -y -qq python3 python3-pip
    useradd -m -s /bin/bash ansible 2>/dev/null || true
    echo "ansible ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ansible
    mkdir -p /home/ansible/.ssh
    echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBhuPxfoR/HA7wfp3pXCN6Bxh+WYz/3W2CJVDkRIw463 ansible_admin@debian" >> /home/ansible/.ssh/authorized_keys
    chmod 700 /home/ansible/.ssh
    chown -R ansible:ansible /home/ansible/.ssh
    echo "PROXY-DMZ (10.0.5.2) prête pour Ansible depuis 10.0.3.2"
  SHELL
end
